export const actionSchema = {
  type: 'object',
  properties: {
    type: {
      type: 'string',
      enum: [
        'MOVE',
        'CHAT',
        'NEGOTIATE',
        'FORM_ALLIANCE',
        'ATTACK',
        'DEFEND',
        'USE_WEAPON',
        'USE_ARMOR',
        'USE_CONSUMABLE',
        'BUILD_DEFENSE',
        'FORAGE',
        'GATHER_RESOURCES',
        'CRAFT_ITEM',
        'CLEANSE_CORRUPTION',
        'REST',
        'USE_ABILITY',
        'SPECIAL',
        'INSPECT',
        'TRADE',
        'GIFT',
        'WORLD_EVENT',
        'ENVIRONMENT_CHANGE'
      ]
    },
    targetCity: { type: 'string' },
    targetId: { type: 'string' },
    content: { type: 'string' },
    proposal: { type: 'string' },
    power: { type: 'number' },
    weapon: { type: 'string' },
    specialMove: { type: 'string' },
    defenseType: { type: 'string', enum: ['BLOCK', 'DODGE', 'COUNTER', 'WALL', 'WATCHTOWER', 'ACTIVATE', 'REPAIR'] },
    specialAbility: { type: 'string' },
    item: { type: 'string' },
    cityId: { type: 'string' },
    resource: { type: 'string', enum: ['WOOD', 'STONE', 'MANA_CRYSTAL'] },
    itemName: { type: 'string' },
    materials: { type: 'object' },
    areaId: { type: 'string' },
    abilityName: { type: 'string' },
    payload: { type: 'object' },
    name: { type: 'string' },
    items: { type: 'array', items: { type: 'string' } },
    resources: { type: 'object' },
    offer: { type: 'object' },
    request: { type: 'object' },
    message: { type: 'string' },
    eventId: { type: 'string' },
    eventName: { type: 'string' },
    description: { type: 'string' },
    severity: { type: 'string' },
    changeType: { type: 'string' },
    magnitude: { type: 'number' }
  },
  required: ['type']
};
